server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: neo4j+s://90a7056c.databases.neo4j.io
    authentication:
      username: neo4j
      password: NAMFGVS-l1cM52UDr8WblLppxWiIn9aeY9VwYNr3AQc
